#!/bin/bash

# luks-tpm2 -- Manage TPM 2.0 sealed LUKS keys
# Copyright (C) 2018 Corey Hinshaw <coreyhinshaw@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version() {
  echo "luks-tpm2 1.0.0"
}

usage() {
  cat <<EOF
Usage: luks-tpm2 [OPTION]... [DEVICE] ACTION

Actions:
  init       Initialize the LUKS TPM key slot
  temp       Set a temporary LUKS passphrase
  reset      Reset the LUKS TPM key using a passphrase
  replace    Replace (overwrite) a LUKS TPM key

Options:
  -h         Print this help text
  -v         Print version information
  -m PATH    Mount point for the tmpfs file system used to store TPM keyfiles
             Default: /root/keyfs
  -p PATH    Sealed keyfile path
             .priv will be added to the path for the private section and .pub
             will be added for the public portion
             Default: /boot/keyfile  (/boot/keyfile.priv /boot/keyfile.pub)
  -H HEX     The TPM handle of the parent object for the sealed key
             Default: 0x81000001
  -x HEX     Index of the TPM NVRAM area holding the key
  -s NUMBER  Key size in byes
             Default: 32
  -t NUMBER  LUKS slot number for the TPM key
             Default: 1
  -r NUMBER  LUKS slot number for temporary reset passphrase
             Default: 2
  -L STRING  List of PCR banks used to seal LUKS key
             Default: sha1:0,2,4,7
  -l STRING  List of PCR banks used to unseal LUKS key
             Default: <value of -L>
  -T STRING  TCTI module used to communicate with the TPM
             Default: device:/dev/tpmrm0
EOF
}

# Create an initial LUKS key in TPM_KEY_SLOT sealed by the TPM
init_tpm_key() {
  echo "Initializing LUKS TPM key for $ROOT_DEVICE"
  echo "WARNING: This will permanently delete the key in slot $TPM_KEY_SLOT!"
  read -p "Do you wish to proceed? [Y/n] " choice
  if [ "$choice" != "y" ] && [ "$choice" != "Y" ]; then
    RETURN_CODE=0
    return
  fi

  read -s -p "Enter any existing LUKS passphrase: " PASSPHRASE
  echo

  echo "Generating new LUKS key..."
  generate_keyfile

  echo "Removing existing key from slot $TPM_KEY_SLOT..."
  echo $PASSPHRASE | cryptsetup luksKillSlot $ROOT_DEVICE $TPM_KEY_SLOT

  echo "Adding new key to slot $TPM_KEY_SLOT..."
  echo $PASSPHRASE | cryptsetup luksAddKey $ROOT_DEVICE "$KEYFILE" --key-slot $TPM_KEY_SLOT
  addkey=$?

  seal_key
  seal=$?

  if [ $addkey -ne 0 ] || [ $seal -ne 0 ]; then
    echo "There was an error initializing the TPM key in slot $TPM_KEY_SLOT!" >&2
    RETURN_CODE=8
  fi
}

# Set a temporary LUKS passphrase in RESET_KEY_SLOT
add_temp_key() {
  unseal_key

  echo "Preparing to set a temporary LUKS passphrase for $ROOT_DEVICE..."
  cryptsetup luksKillSlot --key-file "$KEYFILE" $ROOT_DEVICE $RESET_KEY_SLOT >/dev/null 2>&1

  if cryptsetup luksAddKey --key-slot $RESET_KEY_SLOT --key-file "$KEYFILE" $ROOT_DEVICE < /dev/tty; then
    echo "After booting into the current kernel, run"
    echo "  luks-tpm2 $(echo $ORIGINAL_ARGS | sed 's/temp$/reset/')"
    echo "to generate a new LUKS key and remove this temporary key"
  else
    echo "A temporary passphrase was not set" >&2
    RETURN_CODE=5
  fi
}

# Reset the TPM LUKS key and remove the temporary passphrase
reset_tpm_key() {
  read -s -p "Enter any existing LUKS passphrase for $ROOT_DEVICE: " PASSPHRASE
  echo

  generate_keyfile

  echo "Removing current TPM key from slot $TPM_KEY_SLOT..."
  echo $PASSPHRASE | cryptsetup luksKillSlot $ROOT_DEVICE $TPM_KEY_SLOT

  echo "Adding new key to slot $TPM_KEY_SLOT..."
  echo $PASSPHRASE | cryptsetup luksAddKey $ROOT_DEVICE "$KEYFILE" --key-slot $TPM_KEY_SLOT
  addkey=$?

  seal_key
  seal=$?

  if [ $addkey -eq 0 ] && [ $seal -eq 0 ]; then
    echo "Removing temporary passphrase from slot $RESET_KEY_SLOT..."
    cryptsetup luksKillSlot --key-file "$KEYFILE" $ROOT_DEVICE $RESET_KEY_SLOT
  else
    echo "There was an error resetting the TPM key in slot $TPM_KEY_SLOT!" >&2
    echo "The temporary reset ket in slot $RESET_KEY_SLOT has not been removed." >&2
    RETURN_CODE=4
  fi
}

# Reaplce the LUKS TPM key with a new value
replace_tpm_key() {
  original_keyfile="$KEYFILE.orig"
  unseal_key
  mv "$KEYFILE" "$original_keyfile"

  generate_keyfile

  echo "Replacing LUKS key in slot $TPM_KEY_SLOT on $ROOT_DEVICE..."
  if cryptsetup luksChangeKey $ROOT_DEVICE "$KEYFILE" --key-slot $TPM_KEY_SLOT --key-file "$original_keyfile"; then
    if ! seal_key; then
      echo "There was an error sealing the new keyfile!" >&2
      RETURN_CODE=7
    fi
  else
    echo "There was an error replacing the TPM key in slot $TPM_KEY_SLOT!" >&2
    RETURN_CODE=6
  fi
}

# Create a temporary in-memory file system to store key files
create_ramfs() {
  mkdir -p "$TMPFS_MOUNT"
  if ! mount ramfs "$TMPFS_MOUNT" -t ramfs -o size=1m; then
    echo "Could not create tmpfs. Aborting..." >&2
    exit 3
  fi
  chmod 700 "$TMPFS_MOUNT"
}

# Remove the temporary in-memory file system
destroy_ramfs() {
  if [ -f "$KEYFILE" ]; then
    dd if=/dev/urandom of="$KEYFILE" bs=$(stat --printf="%s" "$KEYFILE") count=1 conv=notrunc >/dev/null 2>&1
    rm -f "$KEYFILE"
  fi
  umount "$TMPFS_MOUNT"
}

# Unseal a key using the TPM
unseal_key() {
  if use_nvram; then
    echo "Reading key from TPM NVRAM..."
    tpm2_nvread -x $NVRAM_INDEX -a $NVRAM_INDEX -L "$UNSEAL_PCRS" -f "$KEYFILE" >/dev/null
  else
    echo "Usealing keyfile..."
    tpm2_load -H $PARENT_HANDLE -r "$SEALED_KEY_PRIVATE" -u "$SEALED_KEY_PUBLIC" -C "$OBJECT_CONTEXT" >/dev/null
    tpm2_unseal -c "$OBJECT_CONTEXT" -o "$KEYFILE" -L "$UNSEAL_PCRS" >/dev/null
    retval=$?
    rm -f "$OBJECT_CONTEXT"
    return $retval
  fi
}

# Seal a key to the TPM
seal_key() {
  if ! tpm2_createpolicy -P -L "$PCRS" -f "$POLICY_DIGEST" >/dev/null; then
    return 1
  fi

  if use_nvram; then
    echo "Storing key in TPM NVRAM..."
    nvout=$(tpm2_nvrelease -x "$NVRAM_INDEX" -a 0x40000001 2>&1)
    if echo "$nvout" | grep -sqiE 'Error.*0x9a2'; then
      read -s -p "Enter TPM owner password: " tpm_auth_pass
      echo
      [ -n "$tpm_auth_pass" ] && tpm_auth_pass="-P $tpm_auth_pass"

      tpm2_nvrelease -x "$NVRAM_INDEX" -a 0x40000001 $tpm_auth_pass >/dev/null 2>&1
    fi

    tpm2_nvdefine -x "$NVRAM_INDEX" -a 0x40000001 $tpm_auth_pass -L "$POLICY_DIGEST" -s $KEY_SIZE -t "policyread|policywrite" >/dev/null
    tpm2_nvwrite -x "$NVRAM_INDEX" -a "$NVRAM_INDEX" -L "$PCRS" "$KEYFILE" >/dev/null
  else
    echo "Sealing keyfile with the TPM..."
    rm -f "$SEALED_KEY_PRIVATE" "$SEALED_KEY_PUBLIC"

    createout=$(tpm2_create -H "$PARENT_HANDLE" -g sha256 -G keyedhash -A 0x492 -I "$KEYFILE" -L "$POLICY_DIGEST" -r "$SEALED_KEY_PRIVATE" -u "$SEALED_KEY_PUBLIC" 2>&1)
    if echo "$createout" | grep -sqiE 'Error.*0x9a2'; then
      read -s -p "Enter parent key password: " tpm_auth_pass
      echo
      [ -n "$tpm_auth_pass" ] && tpm_auth_pass="-P $tpm_auth_pass"

      tpm2_create -H "$PARENT_HANDLE" -g sha256 -G keyedhash -A 0x492 $tpm_auth_pass -I "$KEYFILE" -L "$POLICY_DIGEST" -r "$SEALED_KEY_PRIVATE" -u "$SEALED_KEY_PUBLIC" >/dev/null
    fi
  fi
  retval=$?

  rm -f "$POLICY_DIGEST"
  return $retval
}

# Determine if we are using NVRAM for key storage
use_nvram() {
  [ -n "$NVRAM_INDEX" ]
}

# Generate a random key of KEY_SIZE bytes
generate_keyfile() {
  dd bs=$KEY_SIZE count=1 if=/dev/urandom of="$KEYFILE" >/dev/null 2>&1
}

# Find first LUKS boock device
find_luks_device() {
  lsblk -pfln -o NAME,FSTYPE | grep crypto_LUKS | head -1 | cut -f1 -d' '
}

# Set default config values and load configuration file
load_defaults() {
  TMPFS_MOUNT=/root/keyfs
  SEALED_KEY_PUBLIC=/boot/keyfile.pub
  SEALED_KEY_PRIVATE=/boot/keyfile.priv
  PARENT_HANDLE="0x81000001"
  NVRAM_INDEX=""
  KEY_SIZE=32
  TPM_KEY_SLOT=1
  RESET_KEY_SLOT=2
  PCRS="sha1:0,2,4,7"
  UNSEAL_PCRS=""
  TPM2TOOLS_TCTI="device:/dev/tpmrm0"

  if [ -z "$CONFFILE" ]; then
    CONFFILE=/etc/default/luks-tpm2
  fi
  if [ -r "$CONFFILE" ]; then
    source "$CONFFILE"
  fi
}

# Parse command line arguments
parse_args() {
  ORIGINAL_ARGS="$@"

  while getopts ":hvm:p:H:x:s:t:r:L:l:T:" opt; do
    case $opt in
      h)
        version
        echo "Manage TPM 2.0 sealed LUKS keys on DEVICE"
        echo
        usage
        exit 0
        ;;
      v)
        version
        exit 0
        ;;
      m)
        TMPFS_MOUNT="$OPTARG"
        ;;
      p)
        SEALED_KEY_PUBLIC="$OPTARG.pub"
        SEALED_KEY_PRIVATE="$OPTARG.priv"
        ;;
      H)
        PARENT_HANDLE="$OPTARG"
        ;;
      x)
        NVRAM_INDEX="$OPTARG"
        ;;
      s)
        if [[ ! $OPTARG =~ ^-?[0-9]+$ ]]; then
          echo "Invalid key size: $OPTARG" >&2
          exit 1
        fi
        TPM_KEY_SLOT=$OPTARG
        ;;
      t)
        if [[ ! $OPTARG =~ ^-?[0-9]+$ ]] || [ $OPTARG -lt 0 ] || [ $OPTARG -gt 7 ]; then
          echo "Invalid TPM key slot: $OPTARG" >&2
          exit 1
        fi
        TPM_KEY_SLOT=$OPTARG
        ;;
      r)
        if [[ ! $OPTARG =~ ^-?[0-9]+$ ]] || [ $OPTARG -lt 0 ] || [ $OPTARG -gt 7 ]; then
          echo "Invalid reset key slot: $OPTARG" >&2
          exit 1
        fi
        RESET_KEY_SLOT=$OPTARG
        ;;
      L)
        PCRS="$OPTARG"
        ;;
      l)
        UNSEAL_PCRS="$OPTARG"
        ;;
      T)
        TPM2TOOLS_TCTI="$OPTARG"
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        usage >&2
        exit 1
        ;;
      :)
        echo "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
    esac
  done

  shift $((OPTIND-1))

  if [ -n "$2" ]; then
    ROOT_DEVICE="$1"
    ACTION="$2"
  elif [ -n "$1" ]; then
    ACTION="$1"
  fi
}

# Set addtional global and environment variables
init_globals() {
  if [ -z $ROOT_DEVICE ]; then
    ROOT_DEVICE="$(find_luks_device)"
  fi
  if [ -z $ROOT_DEVICE ]; then
    echo "LUKS device not found!" >&2
    usage >&2
    exit 1
  fi

  case "$ACTION" in
    init) ACTION=init_tpm_key;;
    temp) ACTION=add_temp_key;;
    reset) ACTION=reset_tpm_key;;
    replace) ACTION=replace_tpm_key;;
    *)
      echo "Invalid action!" >&2
      usage >&2
      exit 1
      ;;
  esac

  if [ -z "$UNSEAL_PCRS" ]; then
    UNSEAL_PCRS="$PCRS"
  fi

  KEYFILE="$TMPFS_MOUNT/keyfile"
  POLICY_DIGEST="$TMPFS_MOUNT/policy.digest"
  OBJECT_CONTEXT="$TMPFS_MOUNT/object.context"
  RETURN_CODE=0

  IFS=: read TPM2TOOLS_TCTI_NAME TPM2TOOLS_DEVICE_FILE <<EOF
$TPM2TOOLS_TCTI
EOF
  unset IFS

  export TPM2TOOLS_TCTI
  export TPM2TOOLS_TCTI_NAME
  if [ -n "$TPM2TOOLS_DEVICE_FILE" ]; then
    export TPM2TOOLS_DEVICE_FILE
  fi
}

# Main entry point
main() {
  load_defaults
  parse_args "$@"
  init_globals

  if [ $EUID -ne 0 ]; then
    echo "Must be run as root" >&2
    exit 2
  fi

  create_ramfs
  $ACTION
  destroy_ramfs

  exit $RETURN_CODE
}

main "$@"

# vim:set ts=2 sw=2 et:
